### ISSUE TITLE
Double clicking on markdown preview while editing text exits edit view without saving

### ISSUE THREAD

**Issue by C7C8** [dvorka/mindforger#1278] opened 2020-03-24 18:42 UTC
While editing markdown, if you double click on the rendered preview Mindforger will exit edit mode without saving, causing a loss of work. I just lost a few paragraphs of text to this...

**Comment by Iznik285** [comment] 2020-04-20 12:52
I have also seen this issue as described above. It would be useful to resolve.

**Comment by dvorka** [comment] 2020-04-20 21:02
@C7C8 @Iznik285 Unfortunately I'm not able to reproduce the bug (on Ubuntu/MindForger 1.52). Can you please share your operating system and MindForger version? (there are different preview implementations for every OS)

I apologize for the problems. I will fix it as soon as I find out how to reproduce the problem. Thank you for the bug report!

**Comment by Iznik285** [comment] 2020-04-21 08:01
I am using Windows 10 / MindForger 1.52.0.

**Comment by C7C8** [comment] 2020-04-21 17:08
I am using Arch Linux / MindForger 1.51.0.

Curiously when I just tried to reproduce it on my end, I was unable to succeed as well. I am seeing if I can recreate it.

**Comment by C7C8** [comment] 2020-04-21 17:10
Update: I *can* reproduce it, but not as was before. I opened a new outline and edited it (without any notes); double clicking now just clears out my edits but does not exit edit mode. This is still roughly the same loss of work though.

**Comment by jest** [comment] 2020-10-31 09:55
The same here... I just lost a quarter of writing.

The good habit is to save often, as double-clicking the preview causes the edit mode to be re-entered, reading the content from the disk, so any unsaved work in the editor is lost.

**Comment by dvorka** [comment] 2022-01-11 23:08
No longer reproducible on 6e87d8cc194ab5a9930723b87423f525599d2d04 + it's possible to disable double-click on preview as action to open O/N in menu `Preferences/View/[ ] double click view to edit`.

**Comment by dvorka** [comment] 2022-01-12 07:39
Fixed by a3c32c5 - will be released with MindForger 1.54.0

**Closed** 2022-03-07 22:09 UTC
Labels: bug :lady_beetle:, critical :feelsgood:, :gift: reproducible, :beer: fixed
