### ISSUE TITLE
High CPU load with blank notebook open

### ISSUE THREAD

**Issue by langfingaz** [dvorka/mindforger#906] opened 2018-12-05 23:48 UTC
Even with a new / blank Markdown file open, MindForger has around 30-50% cpu usage. Think and Autolink are disabled.

There should be nothing to calculate for the cpu. Am I missing any hidden settings?

---
About my system:
Fresh Linux Mint 19 installation with Mate, WQHD screen with HiDPI enabled.

**Comment by dvorka** [comment] 2018-12-12 08:19
@langfingaz unfortunately I can confirm this bug - it's most probably related to #905. I'm facing it as well on both UHD and WQHD monitors - in particular when I use **zooming**. I did just basic debugging and the root cause seems to be Qt web preview component (i.e. it's not the code written by me).

I plan to try newer Qt versions, search Qt bugzilla and do more debugging. The good thing is that I'm able to reproduce the problem, bad thing is that I don't have fix yet.

Please stay tuned.

**Comment by langfingaz** [comment] 2018-12-12 10:23
Then good luck fixing it! I agree that it's probably the same issue as #897. I'll close this one then. Thanks!

**Comment by dvorka** [comment] 2018-12-12 18:45
I will keep this issue open so that I can track that fix will work also for you.

**Comment by dvorka** [comment] 2019-02-02 23:05
Fixed by abbce82

**Closed by dvorka** 2019-02-02 23:05 UTC
Labels: :beetle: bug, :hurtrealbad: major
