### ISSUE TITLE
Mindforger freezes on macOS 10.14.3

### ISSUE THREAD

**Issue by kwrobert** [dvorka/mindforger#1005] opened 2019-03-26 13:39 UTC
Mindforger seems amazing, and I would love to give it a try. However, immediately after opening the latest release (1.49.0, installed via Homebrew) on macOS 10.14.3, I get the spinning rainbow wheel of sadness and Mindforger becomes unresponsive. 

I realize Mindforger clearly states in the documentation that it only supports up to macOS 10.12, but it would be nice to support the latest version of the OS as well. I would be happy to provide any debug logs or additional information, if someone could point me in the right direction. 

For those experiencing the same issue, it is still possible to run Mindforger on later version of macOS by installing XQuartz, running Mindforger within a Docker container, and configuring the container to forward Xserver connections to the Xserver running on your Mac.

Thanks for releasing this app to the public! Kudos for all the hard work you've clearly put into this.

**Comment by nicoNaN** [comment] 2019-03-26 13:53
I was experiencing this as well but stopped seeing the behavior after closing/re-opening a few times. I'm wondering if Thinking/Sleeping mode could be the root cause. Try opening it, letting it sit for a while then interacting. Alternatively, try putting it on Sleeping mode and seeing if it freezes.

**Comment by kwrobert** [comment] 2019-03-26 13:58
Well, I think I have found a solution to this, almost immediately after opening an issue. 

If you start Mindforger from the command line, and provide the `-S` flag, then the problem disappears. Pasting in the relevant part of the command line help message below: 

```
 -S, --disable-web-security     Disable WebEngine security to allow loading of
                                                    images on macOS.
```

Without this flag, I get the rainbow wheel of sadness almost immediately. With this flag, everything seems to be working as expected (although I haven't really tested all the functionality of the application yet). 

I suppose we can close this, but I think something should be added to the documentation or some default configuration for macOS changed so others don't encounter the same problem I did.

**Comment by dvorka** [comment] 2019-04-14 20:27
@kwrobert thank you for describing the problem and finding the solution! I will add it to the documentation. Thanks again!

**Comment by benjaminvdb** [comment] 2019-07-12 10:15
> If you start Mindforger from the command line, and provide the -S flag, then the problem disappears. 
@kwrobert thanks for sharing your solution! Unfortunately, this didn't work for me.

I'm on macOS 10.14.5 and I'm getting the infinite rainbow spinner after opening my first note. I've tried force-quitting the application and restarting a few times and tried turning on sleeping mode, but to no avail.

I'd like like to try MindForger! Is there a way to get some debugging output? The application hangs, but I've no clue what it's doing.

**Closed** 2020-01-20 22:18 UTC
Labels: :bow: adoption, :hourglass: task, critical :feelsgood:
