### ISSUE TITLE
Space before heading

### ISSUE THREAD

**Issue by mseliger** [dvorka/mindforger#1056] opened 2019-09-20 17:34 UTC
When entering a heading as a first line of a note then the programs adds himself a space before the heading.
Original
     '## Test'
After saving
    ' ## Test'

**Comment by stexyz** [comment] 2019-09-20 22:47
If I'm not mistaken this is intended (escaping the `##`) .

The idea is to insert notes (=lvl 2 (`##`) blocks into the outline/document through menu (Note->New).

**Comment by dvorka** [comment] 2022-01-13 23:07
Duplicate of #665

**Closed** 2022-03-08 05:32 UTC
Labels: :link: duplicate, :beer: fixed
