### ISSUE TITLE
Half of notes dissaperared.

### ISSUE THREAD

**Issue by kv-gits** [dvorka/mindforger#900] opened 2018-11-21 07:41 UTC
I use repository in mounted cryptfs. So I usually firsty mount directory with note then start mindforger. Once started before mount. And after that half of notes were deleted from disk.

**Comment by dvorka** [comment] 2018-11-21 19:56
I'm very sorry that you lost your data, but I doubt that it MindForger deleted it:

* MindForger **never** deletes any Markdown documents (Notebooks) - you can grep source code. Even menu `Notebook/Deprecate` just moves Markdown file to Limbo. Nothing is **deleted**.
* MindForger works as follows:
   * On start MindForger loads all data to memory and performs indexation (**nothing is written** to the filesystem - all in memory computations).
   * If you browse/search/... Notebooks/Notes or close/kill MindForger, **nothing is written** to filesystem.  
   * Until you click `Save` when you edit a Note/Notebook nothing is written.

Anyway, to understand what happened I need exact description of what you did so that I can reproduce it. Can you please backup your data and repeat the steps you did to provide such description to me? Perhaps it can help others to avoid such loss.

If you edit Markdown file on the filesystem while MindForger was running, you **may lose data**. As I described above, once repo/file is loaded and indexed, in memory data are used (index built phase is expensive). This is what you must avoid:

* start MindForger and let it open/index Notebook `N`
* use an editor and change `N` on filesystem, save it
* change `N` in in MindForger and it will **override** changes made in editor

Please let me know what was the root cause. Is there any change that you can recover your data by undeleting (or rescue from backup/snapshot)?

**Comment by dvorka** [comment] 2018-11-27 06:44
Closing as not reproducible. Feel free to reopen once you have any additional information.

**Closed by dvorka** 2018-11-27 06:44 UTC
