### ISSUE TITLE
[Bug] Toolbar hides on application close after changing the desktop

### ISSUE THREAD

**Issue by sakkamade** [dvorka/mindforger#1437] opened 2022-01-05 23:34 UTC
**Bug description:**

Well, after I close the Mindforger, **after** I change the desktop MindForger is running on and back, `Show toolbar` option becomes `no` if it was `yes`, and remains `no` if it already was `no`.

I am not experiencing that on release version 1.52.0.

**Expected behaviour:**

MindForger will not do that.

**Environment:**

* MindForger version: 1.53.0 release
* Operating system: Arch Linux
* Git SHA (in case of nightly/custom build): as well as 1.54 dev 37ca69877aff5d73fe447bb15f5b340106183f4f

**Steps to reproduce :lady_beetle::**

1. Start MindForger on Desktop No.1
2. Move to another desktop and back to desktop with Mindforger
   (in my case, I did `Super+2` + `Super+1`)
3. Close MindForger (by either `Ctrl+q` or `Alt+m+x`)
4. See :lady_bug: `:lady_beetle:` -> :lady_beetle: ;)

**Screenshots:**

* (Not sure.)

**Error message or log:**

This is the whole log I'm seeing when I start, do the steps, and close MIndForger.
```bash
$ mindforger
QObject::connect: No such slot m8r::OutlineHeaderEditView::slotSaveNote()

$ 
```

**Comment by dvorka** [comment] 2022-01-06 20:47
@sakkamade definitely reproducible. I'm aware of the problem, however, I wasn't able to find reliable repro - the bug seemed to be intermittent. Your description definitely helps - it seems like and refresh/rendering event causes configuration to change and be persisted. Will see...

**Comment by dvorka** [comment] 2022-01-06 20:51
My hints:

* Repro 1 (macOS):
   * start MindForger
   * make toolbar visible in Preferences
   * **minimize** MindForger window - toolbar visibility is set to `false` and configuration is written 🐞 
   * **maximize** MindForger window
   * 🐞 ... toolbar is no longer visible

**Comment by dvorka** [comment] 2022-01-06 21:21
Fixed by 0969889a5d2bbc5cb50d5ad78097a7839d533655 (`dev/1.54.0` branch).

CC @sakkamade

**Comment by sakkamade** [comment] 2022-01-06 21:43
Just tested, seems to be fixed for me.

Thank you very much!

**Comment by sakkamade** [comment] 2022-01-06 21:51
Hmm. I was too quick to draw the conclusion...

So, it works with steps above, but! here are new steps:
1. Start MindForger
2. Quit MindForger using `xdotool` (and I suspect not only that)
   
#### Note
You can use this command in terminal opened on the same desktop as MindForger:
```bash
xdotool windowquit $(xdotool search --onlyvisible --classname mindforger | head -n 1)
```

**Comment by Iznik285** [comment] 2022-01-09 13:17
Looks like the issue is still on the Windows version. It was fixed with #1391 and with 8bfc0de 1.52.401

### Environment

* Mindforger version: 1.53.506
* Platform: Windows 10 20H2

### Steps to reproduce

Open Mindforger, enable toolbar via menu / adapt / show toolbar
Close Mindforger
Open Mindforger and toolbar is not showing

### Describe what you expected to happen

I would expect it to display or not depending on how I set it in a previous session

**Comment by dvorka** [comment] 2022-01-09 17:22
@sakkamade @Iznik285 thank you for detailed reports.

This 🐞 seems to be problematic - the root cause is that UI framework (Qt) is sending _"spontaneous show and hide events"_ which are causing configuration changes + I cannot distinguish these from true hide/show events that might be performed on the widget by user.

While reading your descriptions, I realised that my fix (which check actual toolbar visibility) will not work e.g. when user will manipulate window (as @sakkamade described) and close MindForger.

Thus the only solution I see is to cut off MindForger's configuration from show/hide events i.e. (spontaneous) show/hide events will be ignored and persisted in configuration. **The only way how to control toolbar visibility will be menu `File/Preferences`** going forward.

**Comment by dvorka** [comment] 2022-01-09 17:55
@sakkamade I wanted to repro your scenario, but unfortunately I have old(er) version of `xdotool` on my main Ubuntu machine which doesn't support `windowquit` yet (just close and kill ... where the problem is not reproducible). Just in case you have time/it is possible for you to test `dev/1.54.0` branch it would help. If not - no problem at all. Thanks!

**Comment by sakkamade** [comment] 2022-01-09 23:44
> The only way how to control toolbar visibility will be menu File/Preferences going forward.

Just curious, what other options to control it used to be there? 

> Just in case you have time/it is possible for you to test dev/1.54.0 branch it would help. 

Tested with latest 4c0b26d7, problem is perfectly fixed for me.

Thank you so much! :heart:

**Comment by sakkamade** [comment] 2022-01-10 00:31
> unfortunately I have old(er) version of xdotool on my main Ubuntu machine which doesn't support windowquit yet

@dvorka On that point, you can also try using a similar program, `wmctrl`, in which case the commands will look:

1. Find out the hex (displayed in the first column, e.g. `0x02400006`) of Mindforger window 
  (Using this directly in command `#2` may cause problems, because terminal may also have **`grep mindforger`** in title, and it lists windows of ALL desktops, so the browser may be caught, either):
    ```bash
    wmctrl -l | grep mindforger
    ```
2. And close:
    ```bash 
    wmctrl -ic *the_hex_from_command_above*
    ```

Rather inconvenient in this state, but, with some effort, can be rewritten into a one-liner.

**Comment by Iznik285** [comment] 2022-01-10 16:49
I am now using 1.53.511 3bee6b65 and can confirm that this is working correctly. Many thanks

**Comment by dvorka** [comment] 2022-01-10 19:00
@sakkamade @Iznik285 thank you for the fix verification!

**Comment by johnblommers** [comment] 2022-03-03 04:33
So I cloned branch `dev/1.54.0` thinking the fix was in. But on Linux PopOS 21.10 (GNOME 40) the toolbar will hide itself at will. Let me try `dev/1.53.511` next.

**Closed** 2022-03-07 22:09 UTC
Labels: bug :lady_beetle:, major :hurtrealbad:, :beer: fixed
