### ISSUE TITLE
[MacOs] Tabs as spaces in editor mode

### ISSUE THREAD

**Issue by hanzyoyo** [dvorka/mindforger#673] opened 2018-07-10 12:10 UTC
I can't seem to have tabs as spaces in the editor mode which makes it hard to create embedded lists with the keyboard (I need to type 4 spaces).

I tried all three 'Editor key binding' from the Adapt menu.

Is there something I'm missing?
Cheers

**Comment by dvorka** [comment] 2018-07-10 12:51
I admit that I didn't get a good idea for key binding - users need "normal" <kbd>Tab</kbd> and I didn't want always replace tab with spaces. Do you have any suggestion? Is there any convention/usual key binding on macOS? For example <kbd>Cmd+Tab</kbd> or <kbd>Ctrl+Tab</kbd>?

**Comment by hanzyoyo** [comment] 2018-07-10 13:50
Good question, I must admit I have no idea as well. I like the fact of
having all tabs replaced by spaces like Eclipse especially if the Markdown
syntax doesn't handle tabs. What behavior would be missing if all tabs are
replaces by spaces?

cmd+Tab is the same as ctrl+tab in Windows to change window rapidly so
probably not the best workaround. opt+tab (alt+tab) seems like a good
candidate but I don't think it will be "trivial" for users

2018-07-10 14:51 GMT+02:00 Martin Dvorak <notifications@github.com>:

**Comment by gekaremi** [comment] 2018-07-10 14:18
Maybe< kbd>Tab</kbd>+<kbd>spacebar</kbd>?

**Comment by dvorka** [comment] 2018-07-11 15:19
> I like the fact of having all tabs replaced by spaces like Eclipse...

I use the same Eclipse configuration when programming in Java - I believe that "4 spaces for tab" is the
only reasonable configuration. However, it's subjective - there are developers who use tabs. Same
for Markdown - I went through original Markdown spec by John Gruber and he mentions both spaces
and tabs. I want to keep freedom to choose between spaces and tabs.

> cmd+Tab is the same as ctrl+tab in Windows to change window rapidly so probably not the best workaround. opt+tab (alt+tab) seems like a good candidate but I don't think it will be "trivial" for users

... + I'm on Ubuntu and <kbd>Alt+tab</kbd> is used to switch applications quickly...

> Maybe Tab+spacebar

The problem is that I need a meta key (Alt/Ctrl/Cmd/Windows/... key), spacebar is "normal" key.

**My conclusion**: I will follow Eclipse (and other IDEs) and add ["Insert spaces for tabs"](https://i.stack.imgur.com/gjB1B.png) to configuration (disabled by default) i.e. I suggest to follow the usual approach. You will just click one checkbox and get desired behavior.

What do you think?

**Comment by dvorka** [comment] 2018-08-31 17:55
Implemented in efc7b45219f9ac92a3f525d5734b303ce3a2a04b (spaces are the default), this feature will be released with the next MF version.

**Closed by dvorka** 2018-08-31 17:55 UTC
Labels: :hurtrealbad: major, :octocat: enhancement
