### ISSUE TITLE
Minor User Interface Issue: Creation of New Notebook should open Notebook

### ISSUE THREAD

**Issue by casperl** [dvorka/mindforger#1335] opened 2020-12-06 08:36 UTC
Environment: MindForger 1.52.0 on highly modified Ubuntu 18:10

Problem: 
* Expected behaviour on creation of New Notebook (Alt-O-N) should be to open new Notebook in Notebook management screen (seen image below)
* Presently a new file simply appears in the Notebooks view that then has to be opened in another step.

Expected behaviour:
* Except in exceptional circumstances, users create New Notebooks in order to work on them right away.  
* Therefore creation of a new Notebook (Alt-O-N) should drop the user into the Notebook Management Screen and not leave the user in either the Notebook View or Dashboard View.

![image](https://user-images.githubusercontent.com/1303185/101275393-eec9bb00-37ad-11eb-978c-aafaf645a8eb.png)

**Comment by dvorka** [comment] 2022-01-08 19:05
Makes sense 👍 + requested by multiple users.

**Comment by dvorka** [comment] 2022-01-10 22:49
Duplicate of #1421

**Comment by dvorka** [comment] 2022-01-10 22:50
Fixed by addd419 - will be released in 1.54.0

**Closed** 2022-03-07 22:09 UTC
Labels: :octocat: enhancement, major :hurtrealbad:, :beer: fixed
