### ISSUE TITLE
weird behaviour when running without cmd arguments (hangup on accessing file system)

### ISSUE THREAD

**Issue by tsieger** [dvorka/mindforger#590] opened 2018-06-15 11:45 UTC
When running MF without cmd args, it behaves in a weird way:
- the Xorg process starts consuming 90% of cpu,
- when accessing file system, e.g. when trying to open a file/dir, or when creating a new Repository (Mind -> New -> Mindforger Repository), and an attempt is made to locate a directory by pressing 'Find Directory', MF hangs up: the "Create new Repository" dialog loses its focus, but no other window gets opened. 
Pressing Esc returns the focus to the "Create new Repository" dialog.

I'm running MF v1.42.0 on 64b Fedora Core 27 on Intel, 
x-org 2.10.5-4.fc27.x86_64, 
qt 5.9.2-2.fc27.x86_64.

**Comment by dvorka** [comment] 2018-06-15 12:27
Congratulations on being the first user to post a bug! :smile: 

In order to fix the problem I need to reproduce it.

* Did you installed `.rpm` or compiled MF?
* Did the problem disappeared after MF restart? Does it persist?
* If the problem persists - can you please run MF with `strace` and attach/paste log to this issue? 
    * `strace mindforger > mf-log.txt 2>&1`
        * Just start MF, let it consume CPU for a few seconds, exit and attach log.
* Does MF thinks or sleeps? (check status bar - there is either `Sleeping` or `Thinking` on the left)
    * If MF thinks, try to change it to sleep: menu `Mind/Sleep`.

MindForger starts as follows:

* It reads configuration from `~/.mindforger.md`
* It opens repository/dir/file listed as `Active repository:`.

I tried to delete/screw active repository path, but MF worked correctly. 

* Is there anything specific about active repository?
* When you open different repository/dir/file from command line (like `mindforger file.md`) does the problem persist?

**Comment by tsieger** [comment] 2018-06-15 13:42
I installed an `.rpm`.

The probelm persist and can be reproduced like this:
1. create an empty dir, go there and run `mindforger .` there.
2. MF is sleeping, and Xorg consumes 90% of cpu
3. try creating a new repo, press "Find directory" - focus gets lost, status bar disappears

Opening another repo works correctly.

strace log: [mf-log.zip](https://github.com/dvorka/mindforger/files/2106157/mf-log.zip)

**Comment by dvorka** [comment] 2018-06-15 16:09
I'm able to reproduce the bug - this helped a lot :+1:

**Comment by dvorka** [comment] 2018-06-16 16:33
callgrind/gprof/strace/qt forum - root cause seems to be `virtual void paintEvent(QPaintEvent* event)`. Code review of all components overriding paintEvent() to be done.

**Comment by dvorka** [comment] 2018-06-16 17:06
Fix will be released in 1.42.10

**Closed** 2018-06-16 17:29 UTC
Labels: :beetle: bug, :feelsgood: critical, :gift: reproducible
